// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/incident.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Incident_ClipClip;
@class TimeDelta;
@class TimeStamp;
@class UUID;
GPB_ENUM_FWD_DECLARE(IncidentSeverity);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - IncidentRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface IncidentRoot : GPBRootObject
@end

#pragma mark - Incident

typedef GPB_ENUM(Incident_FieldNumber) {
  Incident_FieldNumber_Id_p = 1,
  Incident_FieldNumber_Ts = 2,
  Incident_FieldNumber_Severity = 3,
  Incident_FieldNumber_Description_p = 4,
  Incident_FieldNumber_ClipsArray = 10,
};

@interface Incident : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UUID *id_p;
/// Test to see if @c id_p has been set.
@property(nonatomic, readwrite) BOOL hasId_p;

/// Trigger for the event happend at ts.
@property(nonatomic, readwrite, strong, null_resettable) TimeStamp *ts;
/// Test to see if @c ts has been set.
@property(nonatomic, readwrite) BOOL hasTs;

@property(nonatomic, readwrite) enum IncidentSeverity severity;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

/// Total duraction of event is sum of ClipClip durations
/// There is an implication here that the "middle" clips last for 
/// the entire length of the clip, that is, has_duration() returns false.
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Incident_ClipClip*> *clipsArray;
/// The number of items in @c clipsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger clipsArray_Count;

@end

/// Fetches the raw value of a @c Incident's @c severity property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t Incident_Severity_RawValue(Incident *message);
/// Sets the raw value of an @c Incident's @c severity property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetIncident_Severity_RawValue(Incident *message, int32_t value);

#pragma mark - Incident_ClipClip

typedef GPB_ENUM(Incident_ClipClip_FieldNumber) {
  Incident_ClipClip_FieldNumber_Clip = 1,
  Incident_ClipClip_FieldNumber_StartOffset = 2,
  Incident_ClipClip_FieldNumber_Duration = 3,
};

@interface Incident_ClipClip : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UUID *clip;
/// Test to see if @c clip has been set.
@property(nonatomic, readwrite) BOOL hasClip;

/// if missing, beginning of clip
@property(nonatomic, readwrite, strong, null_resettable) TimeDelta *startOffset;
/// Test to see if @c startOffset has been set.
@property(nonatomic, readwrite) BOOL hasStartOffset;

/// if missing, rest of clip
@property(nonatomic, readwrite, strong, null_resettable) TimeDelta *duration;
/// Test to see if @c duration has been set.
@property(nonatomic, readwrite) BOOL hasDuration;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
