// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/schemata.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Camera;
@class Clip;
@class Domain;
@class Location;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SchemataRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface SchemataRoot : GPBRootObject
@end

#pragma mark - CameraSchema

typedef GPB_ENUM(CameraSchema_FieldNumber) {
  CameraSchema_FieldNumber_CameraArray = 1,
};

@interface CameraSchema : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Camera*> *cameraArray;
/// The number of items in @c cameraArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger cameraArray_Count;

@end

#pragma mark - ClipSchema

typedef GPB_ENUM(ClipSchema_FieldNumber) {
  ClipSchema_FieldNumber_ClipArray = 1,
};

@interface ClipSchema : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Clip*> *clipArray;
/// The number of items in @c clipArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger clipArray_Count;

@end

#pragma mark - DomainSchema

typedef GPB_ENUM(DomainSchema_FieldNumber) {
  DomainSchema_FieldNumber_DomainArray = 1,
};

@interface DomainSchema : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Domain*> *domainArray;
/// The number of items in @c domainArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger domainArray_Count;

@end

#pragma mark - LocationSchema

typedef GPB_ENUM(LocationSchema_FieldNumber) {
  LocationSchema_FieldNumber_LocationArray = 1,
};

@interface LocationSchema : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Location*> *locationArray;
/// The number of items in @c locationArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger locationArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
