// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UUID;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum IncidentSeverity

typedef GPB_ENUM(IncidentSeverity) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  IncidentSeverity_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  IncidentSeverity_Informational = 0,
  IncidentSeverity_Warning = 1,
  IncidentSeverity_GeneralAlert = 2,
  IncidentSeverity_IndividualAlert = 3,
};

GPBEnumDescriptor *IncidentSeverity_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL IncidentSeverity_IsValidValue(int32_t value);

#pragma mark - TypesRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface TypesRoot : GPBRootObject
@end

#pragma mark - UUID

typedef GPB_ENUM(UUID_FieldNumber) {
  UUID_FieldNumber_Uuid = 1,
};

@interface UUID : GPBMessage

/// Must always be 16 bytes!
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@end

#pragma mark - TimeStamp

typedef GPB_ENUM(TimeStamp_FieldNumber) {
  TimeStamp_FieldNumber_S = 1,
  TimeStamp_FieldNumber_Ns = 2,
};

@interface TimeStamp : GPBMessage

/// Seconds since Unix epoch
@property(nonatomic, readwrite) int64_t s;

/// +nanoseconds
@property(nonatomic, readwrite) int32_t ns;

@end

#pragma mark - TimeDelta

typedef GPB_ENUM(TimeDelta_FieldNumber) {
  TimeDelta_FieldNumber_S = 1,
  TimeDelta_FieldNumber_Ns = 2,
};

/// Unlikely to even need int32 for deltas, but do it for symmetry!
@interface TimeDelta : GPBMessage

@property(nonatomic, readwrite) int64_t s;

@property(nonatomic, readwrite) int32_t ns;

@end

#pragma mark - Location

typedef GPB_ENUM(Location_FieldNumber) {
  Location_FieldNumber_Id_p = 1,
  Location_FieldNumber_Description_p = 2,
};

@interface Location : GPBMessage

/// TODO(ji): flesh this out
@property(nonatomic, readwrite, strong, null_resettable) UUID *id_p;
/// Test to see if @c id_p has been set.
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
