# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#source "https://github.com/CocoaPods/Old-Specs"

target 'owalMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for owalMobile
  pod 'Firebase/Messaging'

#  target 'owalMobileTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
